- README.md
> test: test for PR

- users/admin.py
나를 몇시간의 구렁텅이로 빠뜨린 커스텀 유저와 커스텀 폼. profile 페이지와 연결할 땐 여기에 시간을 낭비하지 않기 위해 주석을 추가합니다.
> docs: Add comment for custom Forms

- README.md
1. merge 옵션을 사용
2. 치명적이지 않다는 게 보장되면 db.sqlite 파일 지우고 migrate
> docs(migration): About how to resolve migration errors

- templates/profile.html
- users/views.py
작업 내용
--
**수정된 유저 모델에 맞게 기능 일부 수정**
* views.profile
* models.User에 맞춰 수정할 회원 정보 내용 변경(username, email, password => nickname, email, password)
* 회원 정보 수정 후 로그아웃 되지 않도록 수정(update_session_auth_hash(request, user))
* redirect("users:profile") => redirect(reverse("users:profile"))
* profile.html
* models.User에 맞춰 화면에 출력될 내용 수정(username, email, password => nickname, email)
> fix(profile): Update views.profile and profile.html to match models.User

- templates/profile.html
- users/views.py
작업 내용
--
프로필 페이지가 인증 요구, AJAX 도입
* views.profile
* @login_required 데코레이터를 통해 인증되지 않은 사용자가 프로필 페이지에 접근하는 것을 차단했습니다.(이슈 #16 참조)
* JsonResponse를 반환하여 profile.html에서 메시지를 출력할 수 있도록 만들었습니다.
* profile.html
* AJAX를 도입했습니다.(향후 fetch를 사용하도록 수정하겠습니다.)
>  fix(profile): prevent unauthorized access to profile

- templates/profile.html
- users/views.py
작업 내용
--
좀 더 Restful하게 변경
* views.profile
* 기존에 POST 요청을 받아 처리하던 것을 PATCH 요청을 받도록 수정했습니다.
* profile.html에서 JSON 형식으로 요청을 보내기 때문에 request.POST 대신 json.loads(request.body)를 사용하게 되었습니다.
* profile.html
* 기존에 사용하던 $.ajax 대신 fetch를 사용하도록 수정했습니다.
* 요청을 JSON형식으로 보내도록 변경했습니다.
* 기존에 수정이나 삭제 요청을 모두 POST로 처리하던 것을 각각 PATCH와 DELETE로 변경했습니다.
> refactor(profile): Replace POST requests with PATCH and DELETE

- core/settings.py
- products/models.py
- 책 정보 수정 완료 시 수정일이 바뀌지 않는 이슈 해결
- 타임존 세팅
> refactor(products): Modify update time, Set timezone

- products/views.py
- templates/book_detail.html
- templates/update_product.html
Fix issues that allow unauthorized users to update book information close #46
- book.user와 request.user가 같아야 수정, 삭제 버튼이 보이도록 수정
- book.user와 request.user가 같지 않으면 수정 권한이 없다는 메시지 표시 후 book_list로 redirect
- 도서 정보 수정 폼에 원래 정보 표시되도록 수정
> fix(products): Fix update-products issue

- templates/book_detail.html
Error: Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
삭제 버튼이 없어져서 gelElement가 null을 반환 
close #46
visibility: hidden을 적용하여 해결
> fix(products): Fix book_detail issue

- products/views.py
- import 난장판을 조금 정리했습니다
- new_id 함수를 도입하여 unique id를 생성하도록 만들었습니다.
- create_product, update_product에 해당 변동사항을 적용했습니다.
> fix(handle): Create unique handle by last object's pk

- templates/cart_list.html
JS 코드에 let이나 const 키워드 붙인다는 것을 깜빡했습니다
> hotfix(cart): htmlElement not found

- templates/signin.html
- 소셜 로그인 버튼 이미지 추가
- signin.html CSS 수정
> refactor(signin): Add social-login buttons

- templates/checkout.html
issue #84 해결
checkout.html 리팩토링 했습니다.
> refactor(checkout): Modify template for running kakaopay and stripe with merge error

- carts/views.py
- templates/book_detail.html
- templates/checkout.html
#90
- 상품 상세 페이지 (book_detail) 에서 구매, kakaopay 버튼 및 stripe, kakaopay 기능 주석 처리
#91
- 장바구니에서 체크된 상품이 없을 시 주문 상세 페이지(checkout)로 가는 것 막음
> Handling error

- purchases/urls.py
- purchases/views.py
- templates/orders.html
> feat(purchases): Add kakaopay purchases cancel

- products/urls.py
> fix(products): Resolve Not Found error

- products/views.py
- templates/book_detail.html
ISSUE #69 
- 미 로그인 사용자는 카트 버튼을 보지 못하도록 설정
ISSUE #99 
- 상품 등록 또는 수정 시 가격을 100원 이상이어야 하도록 설정
> Not login carts, Set minimum price

- templates/signin.html
- users/views.py
* 로그인 시 에러 발생하면 에러 메시지 보이게 수정
#73
> fix(issue73): Display signin error

- carts/views.py
- templates/book_detail.html
* hidden 속성 display none으로 수정
* 비로그인 유저에게 카트 버튼은 보이고 누를 시, 로그인 페이지로 이동시킵니다.
> fix(cart): Change hidden style, anonymous user redirect login page

- core/db.py
- core/settings.py
- requirements.txt
- 기존 내장 db에서 postgresql로 변경하였습니다.
> refactor(db): Modify db.sqlite3 to PostgreSQL

- templates/social_signup.html
- users/serializers.py
- users/views.py
- 회원가입, 로그인과 동일하게 password_validation.validate_password 함수를 적용
- OAuth 사용한 회원가입 시 유효하지 않은 데이터에 대한 에러 출력
> fix(social-signup): Handle errors for invalid user input

- core/settings.py
- products/views.py
- CORS 설정
- AWS S3의 pre-signed URL로 인한 이미지의 만료 문제 해결
> Set cors and Fix expiration issue with pre-signed URLs

- core/urls.py
- entrypoint.sh
- templates/cart_list.html
- AuthorizationQueryParametersError 해결
- Static url 설정
- entrypoint에 collectstatic 추가
> Fix build error (s3)

- templates/signup.html
- users/serializers.py
- users/views.py
> fix(users): Add validation for email
